// Project Data Replacement File
// Replace the contents of project-data.js with this:

const projectData = {
    "AGW260801": {
        "id": "AG-W-260801",
        "cost": "$500 USD",
        "client": "Ali King",
        "project": "Home Walkthrough",
        "startDate": "01/01/2026",
        "status": "waiting",
        "phase": "3D Modeling & Refinement",
        "lastUpdated": "6 Jan 2026",
        "deadline": "10 Jan 2026",
        "nextMilestone": "Final Review & Approval",
        "pendingAmount": "25$",
        "downloadLink": "https://aman3dpartner.netlify.app/",
        "whatsappLink": "https://wa.me/923010003011"
    },
    "6969WER": {
        "id": "69-6-9WER",
        "cost": "2500",
        "client": "Aman",
        "project": "Client ",
        "startDate": "12 Jan 2026",
        "status": "completed",
        "phase": "modleing",
        "lastUpdated": "12 Jan 2026",
        "deadline": "20 feb",
        "nextMilestone": "final approval",
        "pendingAmount": "NONE",
        "downloadLink": "google.com",
        "whatsappLink": "https://wa.me/923010003011"
    },
    "NEW_PROJECT_CODE": {
        "id": "AG-W-260802",
        "cost": "$500 USD",
        "client": "Ali King",
        "project": "Premium Gym Interior Visualization",
        "startDate": "01/01/2026",
        "status": "completed",
        "phase": "3D Modeling & Refinement",
        "lastUpdated": "6 Jan 2026",
        "deadline": "10 Jan 2026",
        "nextMilestone": "Final Review & Approval",
        "pendingAmount": "25$",
        "downloadLink": "https://aman3dpartner.netlify.app/",
        "whatsappLink": "https://wa.me/923010003011"
    },
    "AGW260802": {
        "id": "AG-W-260802",
        "cost": "$900 USD",
        "client": "Aman",
        "project": "Home Walkthrough",
        "startDate": "01/01/2026",
        "status": "completed",
        "phase": "3D Modeling & Refinement",
        "lastUpdated": "6 Jan 2026",
        "deadline": "10 Jan 2026",
        "nextMilestone": "Final Review & Approval",
        "pendingAmount": "25$",
        "downloadLink": "https://aman3dpartner.netlify.app/",
        "whatsappLink": "https://wa.me/923010003011"
    },
    "AU3M253112": {
        "id": "AU-3M-253112",
        "cost": "$0,000 USD",
        "client": "Client Name",
        "project": "Project Title",
        "startDate": "08/01/2026",
        "status": "progress",
        "phase": "Initial Phase",
        "lastUpdated": "8 Jan 2026",
        "deadline": "20 Jan 2026",
        "nextMilestone": "First Milestone",
        "pendingAmount": "NONE",
        "downloadLink": "#",
        "whatsappLink": "https://wa.me/923010003011"
    },
    "AU3M253113": {
        "id": "AU-3M-253113",
        "cost": "$7000 USD",
        "client": "Shbana",
        "project": "Project Title",
        "startDate": "08/01/2026",
        "status": "progress",
        "phase": "Initial Phase",
        "lastUpdated": "8 Jan 2026",
        "deadline": "20 Jan 2026",
        "nextMilestone": "First Milestone",
        "pendingAmount": "7000",
        "downloadLink": "#",
        "whatsappLink": "https://wa.me/923010003011"
    },
    "VMC26H125W": {
        "id": "VMC-26H125-W",
        "cost": "$1800 USD",
        "client": "Mr. William James",
        "project": "Building Concept Design with 3D Tour",
        "startDate": "08/01/2026",
        "status": "waiting",
        "phase": "Initial Phase",
        "lastUpdated": "8 Jan 2026",
        "deadline": "08 FEB 2026",
        "nextMilestone": "Final Approval",
        "pendingAmount": "NONE",
        "downloadLink": "https://aman3dpartner.netlify.app/",
        "whatsappLink": "https://wa.me/923010003011"
    },
    "1AMANZ1": {
        "id": "1AmanZ1",
        "cost": "$0,000 USD",
        "client": "Client Name",
        "project": "Project Title",
        "startDate": "09/01/2026",
        "status": "progress",
        "phase": "Preparing Concpet Plan",
        "lastUpdated": "9 Jan 2026",
        "deadline": "Date",
        "nextMilestone": "1. Preparing Concpet Plan, 2. Layouts/3D Modeling",
        "pendingAmount": "NONE",
        "downloadLink": "#",
        "whatsappLink": "https://wa.me/923010003011"
    },
    "AMAN00Z": {
        "id": "AMAN00Z",
        "cost": "$0,000 USD",
        "client": "Client Name",
        "project": "Project Title",
        "startDate": "09/01/2026",
        "status": "progress",
        "phase": "1/4\n● Preparing Architectural 2D Concept Plan\n● Refining 2D Plan for 3D Modeling",
        "lastUpdated": "9 Jan 2026",
        "deadline": "16/01/2026",
        "nextMilestone": "1/4\n● Preparing Architectural 2D Concept Plan\n● Refining 2D Plan for 3D Modeling\n\n2/4\n● Preparing 3D Model\n● Working on Lighting & Furniture\n● Working on Texturing\n● Setting Up the Environment\n\n3/4\n● Finalizing the Rendering Setup\n● Rendering Images\n● Rendering Walkthrough Video\n● Working on Add-on\n● Finalizing Video for Review\n\n4/4\n● Project Completed\n● Project in Revision",
        "pendingAmount": "NONE",
        "downloadLink": "#",
        "whatsappLink": "https://wa.me/923010003011"
    }
};

window.projectData = projectData;