window.CMS_DATA = {
  "cms_data_compare_v2": {
    "edit_2": "$50+",
    "edit_3": "Foundation Scope",
    "edit_4": "$500+",
    "edit_5": "Structure Scope",
    "edit_6": "$1k+",
    "edit_7": "Walkthrough Scope",
    "edit_1": "Package Name &amp; Prices Starts from",
    "edit_0": "Compare Packages",
    "edit_38": "<br>",
    "edit_57": "Less Than $500",
    "edit_53": "<br>",
    "edit_49": "<br>",
    "edit_50": "<br>",
    "edit_51": "<br>",
    "edit_8": "2k+",
    "edit_44": "Mood Board&nbsp;",
    "edit_11": "What You'll Get (Final Deliverables)<div><br></div>",
    "edit_10": "3D MODELING+RENDERING IMAGES INCLUDED\n                                <div><br></div><div><br></div>",
    "edit_9": "Masterpiece Scope",
    "edit_14": "FULL PACKAGE +\n                                    PRESENTATION + LIST",
    "edit_58": "Less Than $1k",
    "edit_59": "Less Than $2k",
    "edit_19": "2D Architecture Concept Plans",
    "edit_13": "I need your 3d model to start working.",
    "edit_12": "Necessary\n                                for me to start\n                                working:",
    "cms_103": "<br>",
    "cms_105": "<br>",
    "edit_56": "Total",
    "edit_52": "Purchasing Source List",
    "cms_93": "Revisions",
    "cms_88": "Permit Layouts",
    "edit_48": "Conceptual Layout",
    "cms_89": "<br>",
    "edit_45": "<br>",
    "edit_46": "<br>",
    "cms_90": "<br>",
    "cms_91": "<br>",
    "cms_92": "✔",
    "cms_67": "✔",
    "cms_2": "\n                                <div class=\"tier-price\" style=\"\">$50+</div>\n                                <div class=\"tier-name\" style=\"\">Foundation Scope</div>\n                            ",
    "cms_5": "\n                                <div class=\"tier-price\" style=\"\">$500+</div>\n                                <div class=\"tier-name\" style=\"\">Structure Scope</div>\n                            ",
    "cms_8": "\n                                <div class=\"tier-price\" style=\"\">$1k+</div>\n                                <div class=\"tier-name\" style=\"\">Interactive Scope</div>\n                            ",
    "cms_11": "\n                                <div class=\"tier-price\" style=\"\">$2k+</div>\n                                <div class=\"tier-name\" style=\"\">Masterpiece Scope</div>\n                            ",
    "edit_40": "360 View",
    "cms_83": "Layout Presentation&nbsp;",
    "edit_37": "<br>",
    "cms_84": "<br>",
    "cms_85": "<br>",
    "cms_86": "<br>",
    "cms_87": "✔",
    "cms_73": "Purchasing Source List",
    "cms_78": "Mood Board",
    "edit_43": "Conceptual Layout Presentation&nbsp;",
    "edit_42": "<br>",
    "edit_41": "<br>",
    "edit_47": "<br>",
    "cms_57": "✔",
    "cms_62": "✔",
    "edit_54": "<br>",
    "edit_55": "<br>",
    "cms_72": "✔",
    "cms_74": "<br>",
    "cms_75": "<br>",
    "cms_76": "<br>",
    "cms_77": "✔",
    "cms_79": "<br>",
    "cms_80": "<br>",
    "cms_81": "<br>",
    "cms_82": "✔",
    "cms_97": "Unlimited",
    "cms_96": "12",
    "cms_95": "8",
    "cms_94": "4",
    "edit_21": "<br>",
    "edit_22": "✔",
    "edit_18": "✔",
    "edit_17": "✔",
    "cms_27": "✔",
    "edit_25": "✔",
    "edit_34": "✔",
    "edit_20": "3D modeling",
    "edit_36": "Architectural walkthrough",
    "edit_32": "Texturing &amp; lighting",
    "cms_104": "<br>",
    "cms_100": "Less Than 1 week",
    "cms_30": "✔",
    "cms_28": "3D modeling",
    "cms_68": "Interactive Walkthrough",
    "cms_1": "Package name &amp; price",
    "cms_17": "\n                                <div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">Foundation Scope</div><div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">+&nbsp;</div><div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">3D MODELING</div><div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">+</div><div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">3D Rendering Images&nbsp; &nbsp;INCLUDED\n                                </div>\n                                <button class=\"btn-outline compact\" data-popup=\"pricing-pro\" style=\"width: 100%; margin-top: 5px;\">View Example</button>\n                            ",
    "cms_19": "\n                                <div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">Foundation</div><div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">&nbsp;+ Structure Scope</div><div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">+</div><div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">3D WALKTHROUGH Video</div><div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\"><br></div><button class=\"btn-outline compact\" data-popup=\"pricing-premium\" style=\"width: 100%; margin-top: 5px;\">View Example</button>\n                            ",
    "cms_21": "\n                                <div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">Foundation<br>&nbsp;+&nbsp;</div><div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">Structure</div><div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">+&nbsp;</div><div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">Interactive Scope</div><div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">+</div><div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">Mood Board</div><div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">+</div><div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">Purchasing Source</div><div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">+</div><div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">Conceptual Layout Presentation</div><div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">+</div><div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">Permit Layouts&nbsp;</div>\n                                <button class=\"btn-outline compact\" data-popup=\"pricing-masterpiece\" style=\"width: 100%; margin-top: 5px;\">View Example</button>\n                            ",
    "cms_14": "What\n                                You'll Get<br><span style=\"font-size: 11px; font-weight: 400; color: var(--text-muted);\">(Final\n                                    Deliverables)</span>",
    "cms_23": "2D Concept&nbsp; Floor Plan",
    "cms_33": "3D Rendering Images",
    "cms_38": "Architectural Walkthrough",
    "cms_43": "Include environment",
    "cms_63": "3D people",
    "cms_48": "Include furniture&nbsp;",
    "cms_53": "Include Elevations/Cut-sections",
    "cms_58": "Texturing &amp; Lighting&nbsp;",
    "cms_98": "Delivery Time&nbsp;",
    "cms_70": "<br>",
    "cms_99": "5 days",
    "cms_101": "Less Than 2 weeks&nbsp;",
    "cms_102": "Less Than a month&nbsp;",
    "cms_108": "<br>",
    "cms_109": "<br>",
    "cms_110": "<br>",
    "cms_111": "<br>",
    "cms_112": "<br>",
    "cms_106": "<br>",
    "cms_107": "<br>",
    "cms_118": "\n                                <div class=\"total-price\" style=\"\">Less Than $2k</div>\n                                <button onclick=\"initiatePlanChat('Interactive Scope ($800)')\" class=\"btn-select\">Select</button>\n                            ",
    "cms_120": "\n                                <div class=\"total-price\" style=\"\">Less Than $5k</div>\n                                <button onclick=\"initiatePlanChat('Masterpiece Scope ($1500)')\" class=\"btn-select\">Select</button>\n                            ",
    "cms_29": "<br>",
    "cms_34": "<br>",
    "cms_39": "<br>",
    "cms_44": "<br>",
    "cms_69": "<br>",
    "cms_64": "<br>",
    "cms_59": "<br>",
    "cms_54": "<br>",
    "cms_49": "<br>",
    "cms_15": "\n                                <div style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700;\">2D ARCHITECTURE\n                                    CONCEPT PLANS</div>\n                                <button class=\"btn-outline compact\" data-popup=\"pricing-basic\" style=\"width: 100%; margin-top: 5px;\">View Example</button>\n                            ",
    "cms_71": "✔",
    "cms_66": "✔",
    "cms_125": "\n                                <div class=\"total-price\" style=\"\">Less Than $5k</div>\n                                <button onclick=\"initiatePlanChat('Masterpiece Scope ($1500)')\" class=\"btn-select\">Select</button>\n                            ",
    "cms_123": "\n                                <div class=\"total-price\" style=\"\">Less Than $2k</div>\n                                <button onclick=\"initiatePlanChat('Interactive Scope ($800)')\" class=\"btn-select\">Select</button>\n                            ",
    "cms_113": "<br>",
    "cms_24": "✔",
    "cms_25": "✔",
    "cms_26": "✔",
    "cms_31": "\n                                <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" stroke=\"#ff8c00\" stroke-width=\"3\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"display: block; margin: 0 auto;\">\n                                    <polyline points=\"20 6 9 17 4 12\"></polyline>\n                                </svg>\n                            ",
    "cms_50": "\n                                <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" stroke=\"#ff8c00\" stroke-width=\"3\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"display: block; margin: 0 auto;\">\n                                    <polyline points=\"20 6 9 17 4 12\"></polyline>\n                                </svg>\n                            ",
    "cms_51": "\n                                <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" stroke=\"#ff8c00\" stroke-width=\"3\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"display: block; margin: 0 auto;\">\n                                    <polyline points=\"20 6 9 17 4 12\"></polyline>\n                                </svg>\n                            ",
    "cmp-val-360-1": "<br>",
    "cmp-val-360-2": "\n                                <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" stroke=\"#ff8c00\" stroke-width=\"3\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"display: block; margin: 0 auto;\">\n                                    <polyline points=\"20 6 9 17 4 12\"></polyline>\n                                </svg>\n                            ",
    "edit_revisions_lbl": "Purchasing Source List&nbsp;",
    "edit_master_revisions": "✔",
    "edit_39": "<div>Interactive</div><div>Walkthrough</div>",
    "cmp-lbl-3d-people": "Texture/Lighting&nbsp;",
    "cms_55": "\n                                <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" stroke=\"#ff8c00\" stroke-width=\"3\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"display: block; margin: 0 auto;\">\n                                    <polyline points=\"20 6 9 17 4 12\"></polyline>\n                                </svg>\n                            ",
    "edit_timeline_lbl": "Permit Layouts&nbsp;",
    "edit_timeline_4": "✔",
    "edit_timeline_3": "<br>",
    "edit_timeline_2": "<br>"
  },
  "cms_data_pricing-basic_v1": {
    "edit_1": "\n                Necessary for me to start working: <br>\n                <strong style=\"color: var(--primary-orange);\">I'll bring your vision to life with your 3D\n                    model.</strong>\n            ",
    "edit_4": "Environment yyyyyyyyy",
    "edit_2": "\n                    Deliverables: <span style=\"color: var(--primary-orange);\">Walkthrough Video only</span>\n                ",
    "edit_3": "\n                        Included:",
    "edit_5": "Furniture and People",
    "edit_6": "Texturing &amp; Lighting",
    "edit_7": "Image Renderings"
  },
  "cms_data_compare_v1": {
    "edit_0": "Compare Packagessss",
    "edit_8": "\n                                <div class=\"tier-price\" data-edit-id=\"edit_9\" contenteditable=\"false\" style=\"outline: none;\">$1k+</div>\n                                <div class=\"tier-name\" data-edit-id=\"edit_10\" contenteditable=\"false\" style=\"outline: none;\">Premium</div>\n                            ",
    "edit_5": "\n                                <div class=\"tier-price\" data-edit-id=\"edit_6\" contenteditable=\"false\" style=\"outline: none;\">$500+</div>\n                                <div class=\"tier-name\" data-edit-id=\"edit_7\" contenteditable=\"false\" style=\"outline: none;\">pro</div>\n                            ",
    "edit_2": "\n                                <div class=\"tier-price\" data-edit-id=\"edit_3\" contenteditable=\"false\" style=\"outline: none;\">$50+</div>\n                                <div class=\"tier-name\" data-edit-id=\"edit_4\" contenteditable=\"false\" style=\"outline: none;\">Basic</div>\n                            ",
    "edit_12": "WALKTHROUGH VIDEO\n                                    ONLY",
    "edit_13": "3D MODELING +\n                                    WALKTHROUGH",
    "edit_14": "CONCEPT PLAN + 3D\n                                    MODEL + WALKTHROUGH",
    "edit_17": "I need your 2d floor plans to start working.\n                            ",
    "edit_1": "Package name &amp; <br><table class=\"compare-table\" style=\"width: 675.125px; color: rgb(245, 245, 245); background-color: rgba(35, 35, 35, 0.95);\"><tbody><tr><td style=\"color: rgb(245, 245, 245); text-align: center; vertical-align: top;\"><div data-edit-id=\"edit_12\" style=\"margin-bottom: 8px; font-size: 12px; font-weight: 700; outline: rgba(255, 165, 0, 0.3) dashed 1px;\">WALKTHROUGH VIDEO ONLY</div><button class=\"btn-outline compact\" data-popup=\"pricing-basic\" style=\"border-color: rgb(205, 133, 63); border-style: solid; border-width: 0.666667px; border-image: none 100% / 1 / 0 stretch; color: rgb(245, 245, 245); transition-property: all; width: 138.781px;\"></button></td></tr></tbody></table>price",
    "edit_11": "What\n                                You'll Get<br><span style=\"font-size: 11px; font-weight: 400; color: var(--text-muted);\">(Final\n                                    Deliverables)</span>",
    "edit_43": "Source file",
    "edit_39": "Architectural walkthrough",
    "edit_59": "Total",
    "edit_55": "Delivery Time",
    "edit_51": "Revisions",
    "edit_44": "✓",
    "edit_19": "2D Floor Plan"
  }
};