window.CMS_DATA = {
  "cms_data_compare_v2": {
    "edit_0": "Compare Packages",
    "edit_1": "Package Name & Prices Starts from",
    "edit_2": "$225",
    "edit_3": "Foundation Scope",
    "edit_4": "$675",
    "edit_5": "Structure Scope",
    "edit_6": "$800",
    "edit_7": "Interactive Scope",
    "edit_9": "Masterpiece Scope",
    "edit_10": "$1500",
    "edit_11": "What You'll Get<br><span style=\"font-size: 11px; font-weight: 400; color: var(--text-muted);\">(Final Deliverables)</span>",
    "edit_19": "2D Floor Plan",
    "edit_revisions_lbl": "Revisions",
    "edit_49": "Unlimited",
    "edit_50": "Unlimited",
    "edit_51": "Unlimited",
    "edit_master_revisions": "Unlimited",
    "edit_timeline_lbl": "Timeline",
    "edit_53": "1 day",
    "edit_timeline_2": "5 days",
    "edit_timeline_3": "7 days",
    "edit_timeline_4": "14 days",
    "edit_total_lbl": "Total",
    "edit_57": "$225",
    "edit_58": "$675",
    "edit_59": "$800",
    "edit_60": "$1500",
    "cmp-lbl-3d-people": "3D people",
    "cmp-lbl-360-view": "360 view",
    "cmp-val-360-1": "-",
    "cmp-val-360-2": '<svg viewBox="0 0 24 24" width="16" height="16" stroke="#ff8c00" stroke-width="3" fill="none" stroke-linecap="round" stroke-linejoin="round" style="display: block; margin: 0 auto;"><polyline points="20 6 9 17 4 12"></polyline></svg>',
    "cmp-val-360-3": '<svg viewBox="0 0 24 24" width="16" height="16" stroke="#ff8c00" stroke-width="3" fill="none" stroke-linecap="round" stroke-linejoin="round" style="display: block; margin: 0 auto;"><polyline points="20 6 9 17 4 12"></polyline></svg>',
    "cmp-val-360-4": '<svg viewBox="0 0 24 24" width="16" height="16" stroke="#ff8c00" stroke-width="3" fill="none" stroke-linecap="round" stroke-linejoin="round" style="display: block; margin: 0 auto;"><polyline points="20 6 9 17 4 12"></polyline></svg>'
  },
  "cms_data_pricing-basic_v2": {
    "edit_0": "Foundation Scope",
    "edit_3": "Deliverables: <span style=\"color: var(--primary-orange);\">2D Architecture Concept Plans</span>",
    "edit_4": "Included:",
    "edit_basic_1": "2D Concept Floor Plan",
    "edit_basic_2": "Unlimited Revisions",
    "edit_basic_3": "5 Days Delivery"
  },
  "cms_data_pricing-pro_v2": {
    "edit_0": "Structure Scope",
    "edit_1": "3D Sketchup Concept Model",
    "edit_3": "Deliverables: <span style=\"color: var(--primary-orange);\">FOUNDATION + 3D MODELING + RENDERING</span>",
    "edit_4": "Included:",
    "edit_pro_1": "2D Concept Floor Plan",
    "edit_pro_2": "3D modeling",
    "edit_pro_3": "3D Rendering Images",
    "edit_pro_4": "Include environment",
    "edit_pro_5": "Include furniture",
    "edit_pro_6": "Include Elevations/Cut-sections",
    "edit_pro_7": "Texturing & Lighting",
    "edit_pro_8": "3D people",
    "edit_pro_9": "Unlimited Revisions",
    "edit_pro_10": "360 view",
    "edit_pro_11": "8 Rendering Images",
    "edit_pro_12": "Less Than 1 week Delivery"
  },
  "cms_data_pricing-premium_v2": {
    "edit_0": "Interactive Scope",
    "edit_1": "2D Architecture Floor Plan (Colored)",
    "edit_2": "3D Model Cutaway",
    "edit_4": "Deliverables: <span style=\"color: var(--primary-orange);\">STRUCTURE + WALKTHROUGH VIDEO</span>",
    "edit_5": "Included:",
    "edit_prem_1": "Structure Scope +",
    "edit_prem_2": "Architectural Walkthrough",
    "edit_prem_3": "3D Rendering Images",
    "edit_prem_4": "Texturing & Lighting",
    "edit_prem_5": "3D people",
    "edit_prem_6": "Unlimited Revisions",
    "edit_prem_7": "360 view",
    "edit_prem_8": "12 Rendering Images",
    "edit_prem_9": "Less Than 2 weeks Delivery"
  },
  "cms_data_pricing-masterpiece_v2": {
    "edit_0": "Masterpiece Scope",
    "edit_1": "Deliverables: <span style=\"color: var(--primary-orange);\">FULL PACKAGE + PRESENTATION + LIST</span>",
    "edit_2": "Included:",
    "edit_master_1": "Interactive Scope +",
    "edit_master_2": "Interactive Walkthrough",
    "edit_master_3": "3D Rendering Images",
    "edit_master_4": "Purchasing Source List",
    "edit_master_5": "Mood Board",
    "edit_master_6": "Layout Presentation",
    "edit_master_7": "Permit Layouts",
    "edit_master_8": "Unlimited Revisions",
    "edit_master_9": "360 view",
    "edit_master_10": "15 Rendering Images",
    "edit_master_11": "Less Than a month Delivery"
  }
};